### ISSUE TITLE
How did you get into programming?

### ISSUE THREAD

**Issue by arthurvr** [darcyclarke/ama#1]

**Comment by darcyclarke** [comment]
I was really into computer games when I was in my early 'teens and wanted to learn how to write and modify "bots" (basically IRC chat and channel bots). Around 14 I also started tinkering with websites and myspace pages for my band at the time. 

The first line of code I can remember writing was a change of a `font-color` attribute. I had somehow figured out how to view-source of a website I liked and saved it locally. I basically learned how powerful coding was when I started poking around with different values and saw things update on the screen. From there I was sold. _`HTML`: the gateway drug for programmers_
