### ISSUE TITLE
What is your greatest strength and weakness?

### ISSUE THREAD

**Issue by sindresorhus** [darcyclarke/ama#11]

**Comment by darcyclarke** [comment]
This is a doozy of a question.

I think my biggest strength is something I call "active-procrastination" (oxymoron). Essentially, when I start getting board or am having trouble focusing on a task I try to switch gears and start working on another aspect of the project or on another project all together. This tends to help me stay productive.

Unfortunately, my weakness is probably the same thing. Although I'd just call it "procrastination". I can have a hard time staying on task unless there's outside pressure or impending deadlines that require me to focus long-term.
