### ISSUE TITLE
What are your resources for staying up to date on the industry as a whole?

### ISSUE THREAD

**Issue by drewminns** [darcyclarke/ama#13]
:+1:

**Comment by darcyclarke** [comment]
I used to use Google Reader religiously. I subscribed to hundreds of blogs and news sources that helped me keep up-to-date. Unfortunately, when it got shut down I didn't really make an effort to transfer to another feed reader. Plus, the industry as a whole kind of lost interest in long-form blog posts. Good, in-depth articles are few and far between these days and it was beginning to be hard to read every article anyway.

As we get more inundated with streams of communication I think it's important to look for patterns in the noise. I try to look and see where the industry is headed. Find trends. One-off opinion pieces or tutorials aren't really worth reading anymore. If I want to learn more on a subject I'll almost always have to dig deeper then that single point of content or context.

That said, I guess my primary news source would still have to be social media. The most interesting or pertinent updates usually bubble to the top. They're hard to ignore. If Facebook creates a new JS library it'll be all over Reddit or Hacker News. If Google or Apple drop a new product there'll be tweets for days. 

It does seem harder to stay up-to-date right now but you really just have to stop caring as much about the granularity of information. Fragmentation and specialization are inevitable in this industry and we'll all probably have to find our niches.
