### ISSUE TITLE
Are you planning on continuing to maintain a javascript webm decoder?

### ISSUE THREAD

**Issue by mathwhiz1212** [darcyclarke/ama#16]
You have a javascript webm decoder here: https://github.com/darcyclarke/vp8-webm-javascript-decoder I am interested in having a javascript webm decoder but have been unable to find one that is being maintained and is not still in beta. Also one that is usable in a regular web server setup without anything fancy. (Javascript libraries are fine.)

**Comment by darcyclarke** [comment]
Hey @mathwhiz1212! I apologize for the EXTREMELY delayed response here.

I obviously haven't spent much time maintaining the webm decode fork I modified back in 2015. Unfortunately, my focus has been elsewhere from the bleeding edge of video on the web these days. I'm sure there's been huge advancements over the past few years (wasm specifically has made it possible to ship a really efficient video decoder within the browser).

**Comment by mathwhiz1212** [comment]
No problem. I have since moved on from the project I was working on.
