### ISSUE TITLE
What drives you to contribute to and create open-source projects?

### ISSUE THREAD

**Issue by darrinhenein** [darcyclarke/ama#2]

**Comment by darcyclarke** [comment]
When I was 15-16 I started creating online graphics tutorials on forums. I really liked the idea of helping other people achieve the same effects I was doing with my design work. It gave me some satisfaction to see my techniques get used/popularized within my small online communities. 

Around the same time I started getting really into software development and was sharing/distributing my "scripts" for free (mostly custom CMS'). I liked the idea of people using my software. It validated that my work was good and relevant. Years later, I think the drive is still partially about validation but also about helping people and giving back.
