### ISSUE TITLE
Describe how ridiculously good your apple crisp is using only emojis

### ISSUE THREAD

**Issue by sindresorhus** [darcyclarke/ama#4]

**Comment by darcyclarke** [comment]
:hotsprings: :nose: :yum: :smirk: :fork_and_knife: :hushed: :lips: :open_mouth: :tongue: :apple: :grin: :sunny: :ice_cream: :apple: :rocket: :tada: :moneybag: :heart_eyes: :sob:

![https://igcdn-photos-c-a.akamaihd.net/hphotos-ak-xaf1/t51.2885-15/11352306_103169403356138_1782128669_n.jpg](https://igcdn-photos-c-a.akamaihd.net/hphotos-ak-xaf1/t51.2885-15/11352306_103169403356138_1782128669_n.jpg)

![https://igcdn-photos-b-a.akamaihd.net/hphotos-ak-xfa1/t51.2885-15/11312375_887284811355929_1545132841_n.jpg](https://igcdn-photos-b-a.akamaihd.net/hphotos-ak-xfa1/t51.2885-15/11312375_887284811355929_1545132841_n.jpg)

![https://igcdn-photos-g-a.akamaihd.net/hphotos-ak-xta1/t51.2885-15/926008_527450190680718_842607633_n.jpg](https://igcdn-photos-g-a.akamaihd.net/hphotos-ak-xta1/t51.2885-15/926008_527450190680718_842607633_n.jpg)

**Comment by sindresorhus** [comment]
:green_apple: :cake: :yum:

**Comment by drewminns** [comment]
:muscle: :+1: <- I've had it. It's incredible.

**Comment by matbeedotcom** [comment]
I feel like this issue can't formally be closed until the entire Apple Crisp has been completed.

**Comment by darrinhenein** [comment]
I sense a rift in our relationship until I taste this apple crisp.

💔

**Comment by bwinton** [comment]
@darrinhenein: I propose @darcyclarke brings some to the Toronto Mozilla office the next time he visits…  (If we had advance notice, we could probably pick up some ice cream to go with it!)

**Comment by darrinhenein** [comment]
@bwinton I second this motion. Ice cream will be provided :)

**Comment by darcyclarke** [comment]
@bwinton @darrinhenein how does next Friday work? Around 3:30-4:00pm. It'll be a surprise for anyone that isn't reading this thread from Moz. And no worries about the ice cream or whipped cream. It's my treat. Payback for all the stickers and the free tee I got from Ricardo :smile: 

I hope this provokes other offices/organizations to think about upping their swag game here in Toronto :stuck_out_tongue:

**Comment by darrinhenein** [comment]
@darcyclarke dang! I'm on PTO from July 15-22 (something about a new kid or something).... August?

**Comment by darcyclarke** [comment]
@darrinhenein August makes more sense. I'm in India and New York from July 19th-August 4th so next week would have been the only time. But yea, lets do early August so you can enjoy some treats!

**Comment by ahmadnassri** [comment]
:clap:
