### ISSUE TITLE
What excites you most about the future of the web?

### ISSUE THREAD

**Issue by sindresorhus** [darcyclarke/ama#6]
So you can answer you own question https://github.com/bwinton/ama/issues/8.

**Comment by darcyclarke** [comment]
Probably Media Source Extensions. I've been preaching about the future of video for about a year now and I'm finally starting to see it become reality. Vine's video implementation on their site is a perfect example of how we can create speedy video experiences with buffers and streams. I'm also excited about the future of CSS. It seems like we're trending away from preprocessors which are mostly ad-hoc, nuanced languages in themselves. It'll be interesting to see what tools/libraries win out (PostCSS or maybe just plain JavaScript-styles).
