### ISSUE TITLE
What does your phone homescreen look like?

### ISSUE THREAD

**Issue by sindresorhus** [darcyclarke/ama#7]
Screenshot please. I ask everyone this as it tells a lot about a person. [Mine for example.](https://github.com/sindresorhus/ama/issues/64)

**Comment by darcyclarke** [comment]
I'll be honest, my home screen is pretty generic... I tend to swipe left a lot (ao)... so I'll post both my home screen and my secondary screen (which really _should be_ my _home screen_). 

![https://dl.dropboxusercontent.com/u/14347480/screen1.png](https://dl.dropboxusercontent.com/u/14347480/screen1.png)
![https://dl.dropboxusercontent.com/u/14347480/screen2.png](https://dl.dropboxusercontent.com/u/14347480/screen2.png)
