### ISSUE TITLE
What does your dev environment look like?

### ISSUE THREAD

**Issue by sindresorhus** [darcyclarke/ama#8]

**Comment by darcyclarke** [comment]
I guess I'll just run through a bunch of my preferred stack and tools: Sublime Text, iTerm 2 (w ZSH), PhotoShop, Illustrator, Sketch, Gulp (a million gulp plugins), Bower, Main-Bower-Files, jQuery, Backbone, LoDash, Jade, Clientjade, Stylus, Jeet, Nib Node, Express, MongoDB, Mongoose, Loopback, CoffeeScript, Wintersmith etc..
