### ISSUE TITLE
What's your favorite gif?

### ISSUE THREAD

**Issue by sindresorhus** [darcyclarke/ama#9]

**Comment by darcyclarke** [comment]
I think I have two (I'm cheating a lot here)... it's either the classic _mind-blown_ or _bees_ gifs.

![http://www.reactiongifs.com/wp-content/uploads/2011/09/mind_blown.gif](http://www.reactiongifs.com/wp-content/uploads/2011/09/mind_blown.gif)

![http://ak-hdl.buzzfed.com/static/2014-07/18/8/enhanced/webdr10/anigif_enhanced-buzz-31782-1405685704-7.gif](http://ak-hdl.buzzfed.com/static/2014-07/18/8/enhanced/webdr10/anigif_enhanced-buzz-31782-1405685704-7.gif)

**Comment by sindresorhus** [comment]
:+1:
